language: node_js
env:
  - NODE_ENV=travis
node_js:
  - "8.9"
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - mysql -e 'create database shop;'
  - mysql -e 'create database blog;'
script:
  - npm run lint
  - npm test
  - npm run test-cov-html
after_success:
  - npm run coverage-report
